import Post from './Post'
import  './styles.css'
import image from './assets/img-cover.png'
import image1 from './assets/img-icon.png'
import image2 from './assets/Shape.svg'
import image3 from './assets/Rectangle 8.4.svg'
import image4 from './assets/Rectangle 8.4.svg'
import image5 from './assets/Rectangle 8.4.svg'
import image6 from './assets/Rectangle 8.4.svg'
import image7 from './assets/Rectangle 13.svg'
import image8 from './assets/Group 15.svg'
import image9 from './assets/Vector.svg'
import image10 from './assets/thought.svg'
import image11 from './assets/tree.svg'
import image12 from './assets/deal.svg'
import image13 from './assets/award.svg'
import image14 from './assets/Rectangle 6.svg'
import image15 from './assets/Rectangle 6.svg'
import image16 from './assets/Rectangle 6.svg'
import image17 from './assets/Rectangle 8.png'
import image18 from './assets/Rectangle 8 (1).png'
import image19 from './assets/Rectangle 8.3.png'
import image20 from './assets/Group (1).svg'
import image21 from './assets/blog.svg'
import image22 from './assets/prototyping.svg'
import image23 from './assets/cpu (1).svg'
import image24 from './assets/hired.svg'
import image25 from './assets/computer.svg'
import image26 from './assets/shield (1).svg'
import image27 from './assets/conversation.svg'
import image28 from './assets/paint-palette.svg'
import image29 from './assets/binary-code.svg'
import image30 from './assets/training.svg'
import image31 from './assets/quote.svg'
import image32 from './assets/Ellipse.png'
import image33 from './assets/Group 25.png'
import image34 from './assets/Rectangle 6.3.png'
import image35 from './assets/Vector (1).png'
import image36 from './assets/Vector (2).png'
import image37 from './assets/Vector 6.2.png'
import image38 from './assets/img-cover.png'

const post = new Post ('Webpack Post Title', image, image1, image2, image3, image4, image5, image6, image7,
 image8, image9, image10, image11, image12, image13, image14, image15, image16,
 image17, image18, image19, image20, image21, image22, image23, image24, image25, image26, image27,
  image28, image29, image30, image31, image32, image33, image34, image35, image36, image37, image38,)

console.log('Post to String', post.toString())